name: call_clock
description: iOS AI语音通话闹钟 - 通过AI大模型实时语音对话唤醒
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI相关
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # 状态管理
  provider: ^6.1.1
  get: ^4.6.6
  
  # 本地存储
  just_audio_web: ^0.4.8
  path_provider: ^2.0.12
  synchronized: ^3.0.1
  shared_preferences: ^2.2.2
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.3
  
  # 闹钟与通知 (iOS)
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  permission_handler: ^11.1.0
  
  # CallKit & VoIP (iOS专用)
  flutter_callkit_incoming: ^2.0.0+1
  
  # 音频处理 (iOS优化)
  record: ^6.1.2
  record_darwin: ^1.2.2
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  flutter_sound: ^9.2.13  # PCM流式播放支持
  volume_controller: ^2.0.7  # 音量控制

  # 网络请求
  http: ^1.1.2
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  
  # 日期时间
  intl: ^0.19.0
  
  # JSON序列化
  json_annotation: ^4.8.1
  
  # iOS工具
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.2
  vibration: ^1.8.4
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.3.0
  crypto: ^3.0.2
  flutter_native_timezone: ^2.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/ringtones/
    - .env



flutter_launcher_icons:
  ios: true
  image_path: assets/images/icon.png
  remove_alpha_ios: true
